#!/usr/bin/env node

var reporter = require("nodeunit").reporters.default;

process.on("uncaughtException", function (err) {
  console.error(err.stack);
  process.exit(1);
});

reporter.run(["tests/conflicts.js"]);
