#!/bin/sh

# Mail logs if we crashed
echo 'Colabcontroller stopped'
if [ $1 -ne 0 ]
then
  HOSTNAME=`hostname`
  echo 'Fuuuuuuuck. Colabcontroller died!'
  (echo "Subject: Colabcontroller crashed on $HOSTNAME. Exit code $1\n"; tail -n 30 ./log/main/current; ) | msmtp "robomails@floobits.com"
  sleep 1
  exit $1
fi
